### ISSUE TITLE
TextField not support

### ISSUE THREAD

**Issue by tkkcc** [only52607/compose-floating-window#3]
i try to use TextField in floating window, but keyboard input doesn't work
```kotlin
            val floatingWindow = ComposeFloatingWindow(applicationContext)
            floatingWindow.setContent {
                var text by remember {
                    mutableStateOf("aaa")
                }
                TextField(text, {
                    text = it
                })
//                FloatingActionButton(
//                    modifier = Modifier.dragFloatingWindow(),
//                    onClick = {
//                        Log.d("", "tap floating button")
//                    }) {
//                    Icon(Icons.Filled.Call, "Call")
//                }
            }
            floatingWindow.show()
```

**Comment by tkkcc** [comment]
it works with only `FLAG_NOT_TOUCH_MODAL`, same as https://github.com/xrubioj/JetpackComposeOverlayTest/issues/1

**Comment by tkkcc** [comment]
it also needs to be `TYPE_PHONE`, to let IME padding work at expected

**Comment by airalpha** [comment]
> it also needs to be `TYPE_PHONE` on android 7, to let IME padding work at expected. and this match behavior of `TYPE_APPLICATION_OVERLAY` on 14

Please can you provide an example ?

**Comment by only52607** [comment]
compose-floating-window allows you to customize the LayoutParams of the floating window, you can modify it to make it work, such as FLAG_NOT_TOUCH_MODAL.
